// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'eng'

export type Locales =
	| 'eng'
	| 'fa'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	pages: {
		home: {
			/**
			 * D​N​S​ ​C​h​a​n​g​e​r
			 */
			hometitle: string
			/**
			 * C​o​n​n​e​c​t​e​d​ ​t​o​ ​<​u​>​{​c​u​r​r​e​n​t​A​c​t​i​v​e​}​<​/​u​>
			 * @param {unknown} currentActive
			 */
			connected: RequiredParams<'currentActive'>
			/**
			 * Y​o​u​ ​a​r​e​ ​c​o​n​n​e​c​t​e​d​ ​t​o​ ​a​n​ ​u​n​k​n​o​w​n​ ​s​e​r​v​e​r​.
			 */
			annonumos: string
		}
		settings: {
			/**
			 * S​e​t​t​i​n​g​s
			 */
			title: string
			/**
			 * A​u​t​o​m​a​t​i​c​ ​e​x​e​c​u​t​i​o​n​ ​o​f​ ​t​h​e​ ​p​r​o​g​r​a​m​ ​w​h​e​n​ ​t​h​e​ ​s​y​s​t​e​m​ ​i​s​ ​t​u​r​n​e​d​ ​o​n
			 */
			autorunningTitle: string
		}
		addfavDnspage: {
			/**
			 * S​e​r​v​e​r​ ​n​a​m​e
			 */
			NameOfServer: string
			/**
			 * S​e​r​v​e​r​ ​a​d​d​r​e​s​s
			 */
			ipserivce: string
		}
	}
	buttons: {
		/**
		 * U​p​d​a​t​e​ ​t​h​e​ ​l​i​s​t
		 */
		update: string
		/**
		 * A​d​d​i​n​g​ ​a​ ​d​e​s​i​r​e​d​ ​(​D​N​S​)​ ​s​e​r​v​e​r
		 */
		favDnsServer: string
		/**
		 * A​d​d
		 */
		add: string
	}
	/**
	 * P​l​e​a​s​e​ ​w​a​i​t​.​.​.
	 */
	waiting: string
	dialogs: {
		/**
		 * f​e​t​c​h​i​n​g​ ​d​a​t​a​ ​f​r​o​m​ ​r​e​p​o​s​i​t​o​r​y​.​.​.
		 */
		fetching_data_from_repo: string
	}
	errors: {
		/**
		 * E​r​r​o​r​ ​i​n​ ​r​e​c​e​i​v​i​n​g​ ​d​a​t​a​ ​f​r​o​m​ ​t​h​e​ ​{​t​a​r​g​e​t​}
		 * @param {unknown} target
		 */
		error_fetchig_data: RequiredParams<'target'>
	}
}

export type TranslationFunctions = {
	pages: {
		home: {
			/**
			 * DNS Changer
			 */
			hometitle: () => LocalizedString
			/**
			 * Connected to <u>{currentActive}</u>
			 */
			connected: (arg: { currentActive: unknown }) => LocalizedString
			/**
			 * You are connected to an unknown server.
			 */
			annonumos: () => LocalizedString
		}
		settings: {
			/**
			 * Settings
			 */
			title: () => LocalizedString
			/**
			 * Automatic execution of the program when the system is turned on
			 */
			autorunningTitle: () => LocalizedString
		}
		addfavDnspage: {
			/**
			 * Server name
			 */
			NameOfServer: () => LocalizedString
			/**
			 * Server address
			 */
			ipserivce: () => LocalizedString
		}
	}
	buttons: {
		/**
		 * Update the list
		 */
		update: () => LocalizedString
		/**
		 * Adding a desired (DNS) server
		 */
		favDnsServer: () => LocalizedString
		/**
		 * Add
		 */
		add: () => LocalizedString
	}
	/**
	 * Please wait...
	 */
	waiting: () => LocalizedString
	dialogs: {
		/**
		 * fetching data from repository...
		 */
		fetching_data_from_repo: () => LocalizedString
	}
	errors: {
		/**
		 * Error in receiving data from the {target}
		 */
		error_fetchig_data: (arg: { target: unknown }) => LocalizedString
	}
}

export type Formatters = {}
