export enum EventsKeys {
  SET_DNS = "dialogs:set-dns",
  CLEAR_DNS = "dialogs:clear-dns",
  ADD_DNS = "dialogs:add-dns",
  RELOAD_SERVER_LIST = "reloadServerList",
  FETCH_DNS_LIST = "dialogs:fetch_dns_list",
  NOTIFICATION = "notification",
  DIALOG_ERROR = "dialogs:d_error",
  OPEN_BROWSER = "dialogs:open_browser",
  GET_CURRENT_ACTIVE = "dialogs:get_current_active",
  DELETE_DNS = "DELETE_DNS",
  TOGGLE_THEME = "ui:toggleTheme",
  GET_SETTINGS = "setting:get",
  SET_NETWORK_INTERFACE = "setting:set_network_interface",
  GET_NETWORK_INTERFACE_LIST = "setting:get_network_interface_list",
  SAVE_SETTINGS = "setting:save",
  TOGGLE_START_UP = "setting:toggleStartUp",
  FLUSHDNS = "dialogs:flushDns",
  PING = "dialogs:ping",
  TOGGLE_PIN = "dialog:togglePin",
  CHECK_UPDATE = "CHECK_UPDATE",
  START_UPDATE = "START_UPDATE",
  UPDATE_PROGRESS = "UPDATE_PROGRESS",
  UPDATE_ERROR = "UPDATE_ERROR",
  CLOSE = "close",
  MINIMIZE = "MINIMIZE_APP",
}
