name: Pull Request Check

on:
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --force

      - name: Type check and build
        run: npm run build:code
